services:
  tomdkd.symfonybundlegeneratorbundle.command.symfonybundlegeneratorgeneratecommand:
    class: Tomdkd\SymfonyBundleGeneratorBundle\Command\SymfonyBundleGeneratorGenerateCommand
    arguments:
      - 'bundle:generate'
      - '@tomdkd.symfonybundlegenerator.controller.symfonybundlegeneratorcontroller'
    tags:
      - { name: 'console.command' }