parameters:
  tomdkd.symfonybundlegenerator.controller.symfonybundlegeneratorcontroller.class: tomdkd\SymfonyBundleGeneratorBundle\Controller\SymfonyBundleGeneratorController

services:
  tomdkd.symfonybundlegenerator.controller.symfonybundlegeneratorcontroller:
    class: '%tomdkd.symfonybundlegenerator.controller.symfonybundlegeneratorcontroller.class%'
    arguments:
      - '%kernel.project_dir%'
